spring.application.name=Trading
# Set the root logging level
logging.level.root=WARN
# Set a specific package to DEBUG
logging.level.com.Assignment.Trading=DEBUG
# Specify the file name or path
logging.file.name=logs/app.log


